In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB
import warnings

warnings.filterwarnings("ignore")#消除警告

#加载数据
iris = datasets.load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target)

#------------------ 创建多项式模型 MultinomialNB ------------------ 
mul_nb = MultinomialNB()
mul_nb.fit(x_train,y_train)

print("---------------------- MultinomialNB ---------------------- ")
print(classification_report(mul_nb.predict(x_test),y_test))
print(confusion_matrix(mul_nb.predict(x_test),y_test))

#------------------ 创建伯努利模型 BernoulliNB ------------------ 
ber_nb = BernoulliNB()
ber_nb.fit(x_train,y_train)

print("---------------------- BernoulliNB ---------------------- ")
print(classification_report(ber_nb.predict(x_test),y_test))
print(confusion_matrix(ber_nb.predict(x_test),y_test))

#------------------ 创建高斯模型 GaussianNB ------------------ 
gau_nb = BernoulliNB()#用于连续型数据
gau_nb.fit(x_train,y_train)

print("---------------------- GaussianNB ---------------------- ")
print(classification_report(gau_nb.predict(x_test),y_test))
print(confusion_matrix(gau_nb.predict(x_test),y_test))





---------------------- MultinomialNB ---------------------- 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.69      0.81        16
           2       0.64      1.00      0.78         9

    accuracy                           0.87        38
   macro avg       0.88      0.90      0.87        38
weighted avg       0.92      0.87      0.87        38

[[13  0  0]
 [ 0 11  5]
 [ 0  0  9]]
---------------------- BernoulliNB ---------------------- 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.29      0.45        38
           2       0.00      0.00      0.00         0

    accuracy                           0.29        38
   macro avg       0.33      0.10      0.15        38
weighted avg       1.00      0.29      0.45        38

[[ 0  0  0]
 [13 11 14]
 [ 0  0  0]]
---------------------- GaussianNB ----------